### ISSUE TITLE
Windows only?

### ISSUE THREAD

**Issue by erm3nda** [131/trayicon#2]
Can't see anywhere a reference about "this is only for windows", and even if the module has been installed under linux, obviosly will never run `trayicon/node_modules/trayicon/rsrcs/trayicon.exe`.

It's ok if it works at least in Windows, but I was looking for something more general.
Would be good to have Linux binary.

**Comment by 131** [comment]
The design is good, and would be working (i guess) for linux binaries, but i lack knowledge of the API involved.
